In [8]:
from PIL import Image
import numpy

In [9]:
im = Image.open('image001.tif')

In [10]:
imarray = numpy.array(im)

In [11]:
imarray

array([[ 193,  192,  200, ...,  252,  263,  263],
       [ 193,  192,  200, ...,  252,  263,  263],
       [ 210,  197,  190, ...,  238,  237,  277],
       ...,
       [ 193,  212,  225, ..., 1374, 1319, 1267],
       [ 236,  238,  210, ..., 1407, 1405, 1221],
       [ 236,  212,  253, ..., 1336, 1229, 1154]], dtype=uint16)

In [12]:
im = Image.open('image002.tif')
numpy.array(im)

array([[ 215,  203,  198, ...,  280,  268,  244],
       [ 215,  203,  198, ...,  280,  268,  244],
       [ 213,  223,  201, ...,  266,  273,  240],
       ...,
       [ 231,  222,  212, ..., 1284, 1340, 1267],
       [ 236,  207,  221, ..., 1376, 1379, 1191],
       [ 221,  233,  207, ..., 1315, 1209, 1172]], dtype=uint16)

In [13]:
im = Image.open('image003.tif')
numpy.array(im)

array([[ 203,  206,  207, ...,  266,  251,  275],
       [ 203,  206,  207, ...,  266,  251,  275],
       [ 191,  188,  234, ...,  263,  232,  255],
       ...,
       [ 230,  218,  206, ..., 1401, 1312, 1227],
       [ 237,  214,  232, ..., 1266, 1248, 1181],
       [ 201,  212,  222, ..., 1364, 1248, 1121]], dtype=uint16)