In [1]:
from PIL import Image
import numpy

In [2]:
im = Image.open('image001.tif')
x = numpy.array(im)
x[-1,:10]

array([7785, 8217, 8130, 7785, 6446, 5539, 4848, 4157, 3632, 3155],
      dtype=uint16)

In [3]:
im = Image.open('image002.tif')
x = numpy.array(im)
x[-1,:10]

array([6273, 6748, 7094, 6230, 5453, 4675, 4502, 4200, 4071, 3414],
      dtype=uint16)

In [4]:
im = Image.open('image002.tif')
x = numpy.array(im)
x[-1,:10]

array([6273, 6748, 7094, 6230, 5453, 4675, 4502, 4200, 4071, 3414],
      dtype=uint16)